### ISSUE TITLE
data dir not in config

### ISSUE THREAD

**Issue by cawfree** [a16z/helios#197]
I just [upgraded](https://github.com/cawfree/react-native-helios/compare/main...cawfree/ef5a6a216f0662d1a9486c8a5260216c61bac80b) `react-native-helios` to commit [`ef5a6a216f0662d1a9486c8a5260216c61bac80b`](https://github.com/a16z/helios/commit/ef5a6a216f0662d1a9486c8a5260216c61bac80b) and have started encountering a failure across all platforms on launch:

__iOS__:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/7922333/218337038-b21df0df-bef1-42e5-be38-a607fb3cfe4b.png">

__Android__:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/7922333/218337027-d9e8f62c-51a5-4a7f-a276-7a07c6dbfe31.png">

At this time, I'm initializing the client as follows (apologies for the formatting):

<img width="459" alt="image" src="https://user-images.githubusercontent.com/7922333/218337340-9149697b-1fb7-4291-928b-ac33c2ac2e0a.png">

Previously, I've treated the config's `data_dir` argument as uninitialized, but it looks like the client may now treat this as a required property. Is this expected behaviour?

**Comment by ncitron** [comment]
If you use the `FileDB` the data dir is required. If you do not want to cache checkpoints (not recommend since being able to use a previously validated checkpoint is good for security), you can use `ConfigDB` as the database generic on client.

Also note that in since version 0.2.0 of Helios, instantiating a client from the builder is generic, so you may see an error if you don't explicitly set the database type. The best way to do this is to use an explicit client type like `Client<FileDB>`.

**Comment by cawfree** [comment]
Hey Nick, thanks so much for the swift response (as ever).

Thanks to your recommendation it was possible to migrate `react-native-helios` up to [`ef5a6a216f0662d1a9486c8a5260216c61bac80b`](https://github.com/a16z/helios/commit/ef5a6a216f0662d1a9486c8a5260216c61bac80b) after specifying the `data_dir`.

In addition, just to let you know I tried out specifying the specific database engine type but this didn't seem to affect the compiled library.

Anyway, great work! Thanks so much for your assistance with this issue.
