### ISSUE TITLE
implement logging rpc methods

### ISSUE THREAD

**Issue by ncitron** [a16z/helios#23]
We currently don't have any of the rpc methods related to fetching logs implemented. There seems to be a lot of them, and I'm not sure which ones dapps use the most (it seems dapps are using logs less and less nowadays). I think the best plan is to use a bunch of dapps and keep track of which of the log methods they are using and implement them.

**Comment by AlbionaHoti** [comment]
Hi @ncitron, I'm new to rust in general, but I just saw the project and good first issue tag, and I'd like to contribute in any way. I'll start researching what rpc methods other dapps use for fetching logs.

**Comment by simon-saliba** [comment]
Hey, I opened a draft PR. I'm not sure if we need some kind of "proof" for logs, as it is done for accounts for example.

**Comment by wighawag** [comment]
+1 for eth_getLogs and chiming it to say that logs are a very important mechanism for fully decentralized apps

@ncitron 
>  (it seems dapps are using logs less and less nowadays)

This only because more and more web3 app relies on third party servers but truly decentralized app will make use of eth_getLogs themselves

Currently working on in-browser generic indexer to faciliate this, see : https://github.com/conquest-eth/ethereum-indexer
